context:
  version: "1.30"

package:
  name: ddrescue
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/ddrescue/ddrescue-${{ version }}.tar.lz
  sha256: 2264622d309d6c87a1cfc19148292b8859a688e9bc02d4702f5cd4f288745542
  file_name: ddrescue-${{ version }}.tar.lz

build:
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - lzip
    - make

tests:
  - script:
      - ddrescue --help

about:
  license: GPL-2.0-or-later
  license_file: ddrescue-${{ version }}/COPYING
  summary: GNU data recovery tool
  homepage: https://www.gnu.org/software/ddrescue/ddrescue.html

extra:
  recipe-maintainers:
    - danielnachun
